name: parquimetro-service

volumes:
  parquimetro_db_data: {}

services:
  api:
    image: caio303/parquimetro-api:latest
    environment:
      PARQUIMETRO_PROFILE: dev
      PARQUIMETRO_DB_USER: postgres
      PARQUIMETRO_DB_PASSWORD: postgres
      PARQUIMETRO_DB_HOST: db
      PARQUIMETRO_DB_PORT: 5432
      PORT: 8080
    networks:
      - parquimetro-net
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - parquimetro_db_data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_parquimetro
    networks:
      - parquimetro-net
    expose:
      - 5432

networks:
  parquimetro-net:
    driver: bridge